name: dart_vue_cli_new_project_demo
author: the author
version: 0.1.0
description: Project description goes here
dependencies:
  browser: any
  dart_to_js_script_rewriter: any
  vue2: ^0.3.0
web:
  compiler:
    debug: dartdevc
transformers:
  - vue2:
      entry_points:
        - web/index.dart
  - dart_to_js_script_rewriter
